services:
  app:
    build: .
    container_name: php_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
      MARIADB_USER: user
      MARIADB_PASSWORD: userpass
    ports:
      - "3306:3306"